import Head from 'next/head'
import Router  from 'next/router'
import { useEffect } from 'react'
import Stripe from 'stripe'
import PurchaseCard from '../components/PurchaseCard'
import { useAppContext } from '../context/CardContext'

export async function getServerSideProps(context) {
  const stripe = new Stripe(process.env.STRIPE_SECRET ?? '', {
    apiVersion: '2022-11-15'
  })

  const response = await stripe.prices.list({
    limit: 6,
    expand: ['data.product']
  })

  const prices = response.data.filter(price => price.active)

  return {
    //Renamed from prices to items as it is data of items
    props: {prices}
  }
}
export default function Home({ prices }) {
  const {state, dispatch} = useAppContext()

  async function checkout() {
    const lineItems = [{
      price: prices[0].id,
      quantity: 1
    }]

    const res = await fetch('api/checkout', {
      method: 'POST',
      body: JSON.stringify({ lineItems })
    })

    const data = await res.json()
    // console.log(data )

   Router.push(data.session.url)
  }

  useEffect(() => {
    dispatch({
      type: 'set_prices',
      value: prices
    })
  }, [prices])

  console.log(prices)

  return (
    <div>
      <Head>
        <title>Marcy Trees Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br></br>
      {prices.map((price, index) => {
        return <PurchaseCard price={price} key={index}/>
      })}

    </div>
  )
}
